// Legal.tsx — Terms of Service + Privacy Policy for ResumeLens
// Reachable at /legal, /terms, /privacy

function ResumeLensLogoSmall() {
  return (
    <svg width="28" height="28" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
      <rect x="4" y="2" width="18" height="22" rx="2" fill="#eab308" opacity="0.15" />
      <rect x="4" y="2" width="18" height="22" rx="2" fill="none" stroke="#eab308" strokeWidth="1.5" />
      <circle cx="22" cy="22" r="6" fill="#1c1917" stroke="#facc15" strokeWidth="2" />
      <line x1="26.5" y1="26.5" x2="30" y2="30" stroke="#facc15" strokeWidth="2" strokeLinecap="round" />
    </svg>
  );
}

export default function Legal() {
  const updated = "June 2026";
  return (
    <div className="min-h-screen bg-stone-50 text-stone-800">
      {/* Header */}
      <header className="bg-white border-b border-stone-200 sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <a href="/" className="flex items-center gap-2 font-black text-stone-900">
            <ResumeLensLogoSmall /> ResumeLens
          </a>
          <a href="/" className="text-sm font-semibold text-stone-500 hover:text-stone-900">← Back to site</a>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-10 prose-stone">
        <h1 className="text-3xl font-black text-stone-900 mb-2">Terms of Service & Privacy Policy</h1>
        <p className="text-stone-400 text-sm mb-8">Last updated: {updated}</p>

        {/* ---------- TERMS ---------- */}
        <section className="mb-12">
          <h2 className="text-xl font-bold text-stone-900 mb-4 pb-2 border-b border-stone-200">Terms of Service</h2>

          <div className="space-y-5 text-sm leading-relaxed text-stone-600">
            <div>
              <h3 className="font-bold text-stone-800 mb-1">1. Overview</h3>
              <p>ResumeLens ("we," "us," "the Service") is an online tool that provides AI-assisted resume analysis, resume building, and related career document features. By accessing or using ResumeLens at resumelenz.com, you agree to these Terms of Service. If you do not agree, please do not use the Service.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">2. The Service</h3>
              <p>ResumeLens offers free features including resume analysis, an ATS compatibility score, and a resume builder. Certain premium features (such as AI resume rewriting, cover letter generation, and LinkedIn optimization) are available through a one-time payment. We may add, change, or remove features at any time.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">3. Not Career or Legal Advice; No Guarantees</h3>
              <p>ResumeLens provides automated suggestions generated by artificial intelligence. Our feedback, scores, and suggestions are for informational purposes only and are not a guarantee of employment, interviews, or any specific job outcome. We do not guarantee that any resume will pass a particular employer's applicant tracking system. You are responsible for reviewing and verifying all content before using it.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">4. Payments and Refunds</h3>
              <p>Premium features are offered for a one-time payment as displayed at checkout. Payments are processed securely by our third-party payment provider (Lemon Squeezy); we do not store your card details. Because premium features deliver digital results immediately, refunds are handled on a case-by-case basis — if you experience a technical problem that prevents you from receiving what you paid for, contact us and we will work to make it right.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">5. Acceptable Use</h3>
              <p>You agree to use ResumeLens only for lawful purposes and to submit only content you have the right to use. You agree not to misuse the Service, attempt to disrupt it, or use it to process content that is unlawful or infringes others' rights.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">6. Intellectual Property</h3>
              <p>The ResumeLens name, design, and software are owned by us. Content you upload remains yours; resumes and documents you create with the builder belong to you.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">7. Limitation of Liability</h3>
              <p>The Service is provided "as is" without warranties of any kind. To the fullest extent permitted by law, ResumeLens shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service, including any employment decisions made based on its output.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">8. Changes to These Terms</h3>
              <p>We may update these Terms from time to time. Continued use of the Service after changes means you accept the updated Terms.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">9. Contact</h3>
              <p>Questions about these Terms? Contact us at the email address listed on resumelenz.com.</p>
            </div>
          </div>
        </section>

        {/* ---------- PRIVACY ---------- */}
        <section>
          <h2 className="text-xl font-bold text-stone-900 mb-4 pb-2 border-b border-stone-200">Privacy Policy</h2>

          <div className="space-y-5 text-sm leading-relaxed text-stone-600">
            <div>
              <h3 className="font-bold text-stone-800 mb-1">1. What We Collect</h3>
              <p>We collect the email address you provide to view your results, and any feedback you choose to submit. When you analyze a resume, the text of that resume is processed to generate your analysis.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">2. Your Resume Content</h3>
              <p>Resume text you submit is sent to our analysis service to generate feedback. We do not sell your resume content. Resume files are processed to produce your results and are not permanently stored on our servers for the purpose of building a profile on you.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">3. How We Use Your Information</h3>
              <p>We use your email to deliver results, send you product updates if you opt in, and improve the Service. We use aggregated, non-identifying feedback to make ResumeLens better.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">4. Third-Party Services</h3>
              <p>We rely on trusted third parties to operate: a payment processor (Lemon Squeezy) for purchases, an AI provider to generate analysis, and hosting/analytics providers. These services have their own privacy policies. Your payment card details are handled entirely by the payment processor and are never seen or stored by us.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">5. Cookies and Analytics</h3>
              <p>We may use basic analytics to understand how visitors use the site (for example, how many people visit a page). This helps us improve the Service.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">6. Your Choices</h3>
              <p>You may request that we delete your email from our records by contacting us. You can choose not to provide a resume or email, though some features require them to function.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">7. Children</h3>
              <p>ResumeLens is intended for users who are at least 16 years old and seeking employment. It is not directed at children.</p>
            </div>

            <div>
              <h3 className="font-bold text-stone-800 mb-1">8. Contact</h3>
              <p>For privacy questions or requests, contact us at the email address listed on resumelenz.com.</p>
            </div>
          </div>
        </section>

        <p className="text-stone-400 text-xs mt-12 pb-8">© {new Date().getFullYear()} ResumeLens. All rights reserved.</p>
      </main>
    </div>
  );
}